// SASP placeholder data — Italian retail bank, personal loan for young professionals (25–35)

const ARCHETYPES = [
  {
    id: 'marco',
    name: 'Marco',
    age: 34,
    tagline: 'Risk-averse renter comparing mortgage and protection cover',
    region: 'Milan',
    income: '€38–46k',
    lifeStage: 'Renting, partnered, no kids',
    job: 'Mid-level designer at a SaaS company',
    portrait: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=480&q=80&auto=format&fit=crop',
    accent: 'green',
    matchScore: 87,
    crmMatches: 1240,
    rate:    { min: 4.8, max: 5.8, sweet: 5.4 },
    term:    { min: 36,  max: 72,  sweet: 60  },
    channel:    'hybrid',
    comms:      'friendly',
    likes:    ['transparent APR', 'no hidden fees', 'mobile-first', 'fixed rate', 'clear amortization'],
    distrust: ['big banks', 'long contracts', 'bundled insurance upsell'],
    summary: "Researches everything twice. Has a spreadsheet with every bank's TAEG, TAN, fees, and payment-protection add-ons. Will switch in a heartbeat if a competitor undercuts.",
    quotes: [
      { source:'reddit', sub:'r/ItalyPersonalFinance', author:'u/marco_milano', text:"Looked at five banks for a personal loan and the only one with a clear amortization table was the smallest one. The big ones bury fees in the fine print." },
      { source:'reddit', sub:'r/personalfinance',     author:'u/quietsaver',  text:"Fixed rate every time. I don't sleep well with variable, even if it's slightly cheaper on paper." },
      { source:'x',      handle:'@marcoinmi',          text:"Cool, another bank ad with 'starting from 4.9%' that turns into 6.7% once you add the insurance you can't refuse." },
      { source:'reddit', sub:'r/Fire',                  author:'u/3pct_rule',   text:"Anyone else just open the app, see the full repayment schedule, and only then decide? That's the bare minimum." },
    ],
    internal: '1,240 bank CRM records match this profile (renters, 30–35, salaried, Milan/Turin/Bologna).',
  },
  {
    id: 'sofia',
    name: 'Sofia',
    age: 29,
    tagline: 'Freelance borrower with irregular income and thin underwriting file',
    region: 'Bologna',
    income: '€22–48k variable',
    lifeStage: 'Single, P. IVA forfettario',
    job: 'Self-employed copywriter',
    portrait: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=480&q=80&auto=format&fit=crop',
    accent: 'green',
    matchScore: 79,
    crmMatches: 480,
    rate:    { min: 5.0, max: 6.4, sweet: 5.7 },
    term:    { min: 24,  max: 60,  sweet: 48  },
    channel:    'digital',
    comms:      'friendly',
    likes:    ['flexible installments', 'pause months', 'digital signature', 'no branch visits', 'transparent pricing'],
    distrust: ['rigid repayment schedules', 'KYC and income-proof red tape'],
    summary: "Income swings month to month. Cares less about headline APR than whether the product gives her cash-flow relief when a client pays late.",
    quotes: [
      { source:'x',      handle:'@sofiawrites',         text:"Banks treating freelancers like a credit risk in 2026 is wild. My income over 3 years is more stable than half my employed friends'." },
      { source:'reddit', sub:'r/ItalyPersonalFinance', author:'u/partita_iva_life', text:"The only product that ever made sense for me had a 'salta una rata' option twice a year. Everything else assumes you get paid on the 27th." },
      { source:'x',      handle:'@bolognaUX',           text:"If you make me upload three payslips I don't have, you don't actually want freelance customers." },
    ],
    internal: '480 bank CRM records with P. IVA forfettario classification.',
  },
  {
    id: 'luca',
    name: 'Luca',
    age: 32,
    tagline: 'Dual-income household optimizing rates, deposits, and cover',
    region: 'Turin',
    income: '€68–80k household',
    lifeStage: 'Married, planning first child',
    job: 'Engineering manager',
    portrait: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=480&q=80&auto=format&fit=crop',
    accent: 'green',
    matchScore: 82,
    crmMatches: 920,
    rate:    { min: 4.2, max: 5.4, sweet: 4.9 },
    term:    { min: 24,  max: 48,  sweet: 36  },
    channel:    'digital',
    comms:      'technical',
    likes:    ['early repayment', 'API access', 'best APR', 'open-banking pull', 'detailed breakdowns'],
    distrust: ['relationship managers', 'phone calls', 'paper'],
    summary: "Will repay early if there is no penalty. Wants side-by-side comparison with his primary bank, deposit returns, and any required insurance cover. Reads the prospectus.",
    quotes: [
      { source:'reddit', sub:'r/Fire',                 author:'u/optimizer_to', text:"Always negotiate the early-repayment clause. The default is fine for the bank, terrible for you. Half a point lower beats most cashback offers." },
      { source:'x',      handle:'@luca_eng',           text:"If I can't see the full TAEG with one click I assume you're hiding something." },
      { source:'reddit', sub:'r/personalfinance',     author:'u/coffee_indexes', text:"36 months over 60. Less interest, fewer surprises, done." },
    ],
    internal: '920 bank CRM records in dual-income brackets, ages 30–35.',
  },
  {
    id: 'giulia',
    name: 'Giulia',
    age: 27,
    tagline: 'Recent expat returnee rebuilding credit bureau history',
    region: 'Rome',
    income: '€32–38k',
    lifeStage: 'Single, just back from Berlin',
    job: 'Data analyst at a bank (not ours)',
    portrait: 'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=480&q=80&auto=format&fit=crop',
    accent: 'green',
    matchScore: 71,
    crmMatches: 210,
    rate:    { min: 5.2, max: 6.6, sweet: 5.9 },
    term:    { min: 36,  max: 60,  sweet: 48  },
    channel:    'digital',
    comms:      'formal',
    likes:    ['English-language docs', 'fast onboarding', 'SPID login', 'no in-branch visits'],
    distrust: ['Italian-only paperwork', 'fax machines', 'queue numbers'],
    summary: "Spent four years abroad. CRIF profile is thin. Wants the digital banking, onboarding, and credit decisioning experience she had in Germany, in Italy.",
    quotes: [
      { source:'reddit', sub:'r/ItalyPersonalFinance', author:'u/back_to_rome', text:"Came back after 4 years in Berlin. CRIF basically forgot I exist. Two banks rejected me on data, not credit." },
      { source:'x',      handle:'@giuliaback',         text:"Why is the only bank with a usable English UI a neobank with no Italian license for personal loans?" },
      { source:'reddit', sub:'r/expats',               author:'u/eu_returnee',   text:"SPID + IBAN should be enough to onboard. It is, in some banks. Just not the one I bank with." },
    ],
    internal: '210 bank CRM records flagged as recent EU returnees.',
  },
  {
    id: 'davide',
    name: 'Davide',
    age: 31,
    tagline: 'Side-hustling borrower, working-capital curious',
    region: 'Naples',
    income: '€34k + side',
    lifeStage: 'Renting with friends',
    job: 'Public-sector employee + e-commerce side',
    portrait: 'https://images.unsplash.com/photo-1463453091185-61582044d556?w=480&q=80&auto=format&fit=crop',
    accent: 'green',
    matchScore: 68,
    crmMatches: 360,
    rate:    { min: 4.6, max: 5.8, sweet: 5.2 },
    term:    { min: 12,  max: 36,  sweet: 24  },
    channel:    'digital',
    comms:      'friendly',
    likes:    ['short term', 'working capital', 'fast disbursement', 'no insurance bundle'],
    distrust: ['mandatory insurance', 'long terms', 'branch managers'],
    summary: "Wants the credit disbursed yesterday so he can fund inventory for his side-shop. Hates opaque advisory language and mandatory PPI add-ons.",
    quotes: [
      { source:'x',      handle:'@davide_napoli',     text:"If your loan offer requires me to schedule a 'consulenza' I'm out. Just give me the rate." },
      { source:'reddit', sub:'r/ItalyPersonalFinance', author:'u/sidehustle_na',  text:"Got the loan in 4 working days. Other bank wanted 11. Speed is the product." },
      { source:'reddit', sub:'r/personalfinance',     author:'u/mini_inventory', text:"Short term, no insurance, paid off in 18. The trick is not getting talked into the 5-year option." },
    ],
    internal: '360 bank CRM records with declared secondary income.',
  },
  {
    id: 'elena',
    name: 'Elena',
    age: 26,
    tagline: 'First-time borrower, advice-seeking retail customer',
    region: 'Florence',
    income: '€28–32k',
    lifeStage: 'Living with parents',
    job: 'Junior accountant',
    portrait: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=480&q=80&auto=format&fit=crop',
    accent: 'green',
    matchScore: 74,
    crmMatches: 540,
    rate:    { min: 5.4, max: 6.8, sweet: 6.1 },
    term:    { min: 36,  max: 72,  sweet: 60  },
    channel:    'hybrid',
    comms:      'friendly',
    likes:    ['advisor available', 'predictable installments', 'reassurance', 'simple language'],
    distrust: ['fine print', 'jargon', 'aggressive marketing'],
    summary: "First loan ever. Wants someone to explain APR, installment risk, and optional insurance clearly. Will choose the bank her parents trust if the rate is within half a point.",
    quotes: [
      { source:'reddit', sub:'r/ItalyPersonalFinance', author:'u/elena_fi', text:"This is my first loan, can someone explain TAEG vs TAN like I'm five? The bank app definitely won't." },
      { source:'x',      handle:'@elenafirenze',      text:"Walked into a branch just to be told 'do it on the app'. Then I open the app and it tells me to call the branch. Make it stop." },
      { source:'reddit', sub:'r/personalfinance',    author:'u/firsttime',     text:"I think I want a longer term so the monthly is small enough to ignore. Is that bad?" },
    ],
    internal: '540 bank CRM records under 28 with no prior loan products.',
  },
];

const PRODUCT_DEFAULTS = {
  type: 'Personal loan',
  rate: 6.2,        // %
  term: 60,         // months
  amount: 12000,    // €
  upfrontFee: 1.2,  // %
  repaymentCadence: 'monthly',
  features: {
    digitalOnly: true,
    advisor: false,
    earlyExitWaiver: false,
    loyaltyPerk: false,
    flexiblePause: false,
    insuranceBundle: false,
    salarySwitch: false,
    jointApplication: false,
  },
};

const TENANTS_DATA = [
  {
    id: 'banca-esempio',
    name: 'Banca Esempio Italia',
    plan: 'Enterprise',
    region: 'Italy',
    products: [
      {
        id: 'personal-loan-young-pros',
        name: 'Digital Personal Loan',
        segment: 'Young Professionals 25-35',
        type: 'Personal loan',
        status: 'v0.4 draft',
        rate: 6.2,
        term: 60,
        amount: 12000,
        items: '12,718',
        upfrontFee: 1.1,
        repaymentCadence: 'monthly',
        features: { digitalOnly: true, advisor: false, earlyExitWaiver: false, flexiblePause: false, insuranceBundle: false, salarySwitch: false, jointApplication: false },
      },
      {
        id: 'green-mortgage',
        name: 'Green Home Mortgage',
        segment: 'First-home buyers',
        type: 'Mortgage',
        status: 'v0.2 concept',
        rate: 4.85,
        term: 72,
        amount: 240000,
        items: '8,441',
        upfrontFee: 0.8,
        repaymentCadence: 'monthly',
        features: { digitalOnly: false, advisor: true, earlyExitWaiver: true, flexiblePause: false, insuranceBundle: false, salarySwitch: true, jointApplication: true },
      },
      {
        id: 'flex-savings',
        name: 'Flexible Deposit Account',
        segment: 'Mass affluent savers',
        type: 'Deposit',
        status: 'v0.1 test',
        rate: 3.1,
        term: 24,
        amount: 18000,
        items: '5,214',
        upfrontFee: 0.4,
        repaymentCadence: 'monthly',
        features: { digitalOnly: true, advisor: true, earlyExitWaiver: true, flexiblePause: true, insuranceBundle: false, salarySwitch: true, jointApplication: false },
      },
    ],
  },
  {
    id: 'nord-credit',
    name: 'Nord Credit Union',
    plan: 'Growth',
    region: 'Nordics',
    products: [
      {
        id: 'startup-credit-line',
        name: 'SME Working Capital Line',
        segment: 'Founder-led SMEs',
        type: 'SME credit',
        status: 'pilot',
        rate: 7.1,
        term: 48,
        amount: 35000,
        items: '4,880',
        upfrontFee: 1.6,
        repaymentCadence: 'monthly',
        features: { digitalOnly: true, advisor: true, earlyExitWaiver: true, flexiblePause: true, insuranceBundle: false, salarySwitch: true, jointApplication: false },
      },
      {
        id: 'retirement-bridge',
        name: 'Pension Bridge Plan',
        segment: 'Late-career planners',
        type: 'Pension',
        status: 'research',
        rate: 5.4,
        term: 72,
        amount: 22000,
        items: '3,102',
        upfrontFee: 0.9,
        repaymentCadence: 'monthly',
        features: { digitalOnly: false, advisor: true, earlyExitWaiver: false, flexiblePause: false, insuranceBundle: true, salarySwitch: false, jointApplication: false },
      },
    ],
  },
  {
    id: 'med-finance',
    name: 'Med Bancassurance Lab',
    plan: 'Sandbox',
    region: 'Spain',
    products: [
      {
        id: 'clinic-equipment-loan',
        name: 'Clinic Equipment Finance',
        segment: 'Independent clinics',
        type: 'SME credit',
        status: 'demo',
        rate: 6.75,
        term: 60,
        amount: 42000,
        items: '2,776',
        upfrontFee: 1.4,
        repaymentCadence: 'monthly',
        features: { digitalOnly: true, advisor: true, earlyExitWaiver: false, flexiblePause: true, insuranceBundle: false, salarySwitch: true, jointApplication: false },
      },
      {
        id: 'family-protection',
        name: 'Family Protection Cover',
        segment: 'New parents',
        type: 'Protection insurance',
        status: 'draft',
        rate: 5.9,
        term: 36,
        amount: 9000,
        items: '3,641',
        upfrontFee: 0.7,
        repaymentCadence: 'monthly',
        features: { digitalOnly: true, advisor: false, earlyExitWaiver: false, flexiblePause: false, insuranceBundle: true, salarySwitch: false, jointApplication: true },
      },
    ],
  },
];

const SOURCES_DATA = {
  company: [
    { id:'gdrive',  name:'Google Drive',     status:'connected', last:'2 min ago',   count:'240 docs',     hint:'Credit policy, policy wording, customer interviews, market research' },
    { id:'web',     name:'Website crawl',    status:'connected', last:'14 min ago',  count:'78 pages',     hint:'banca-example.it — products, disclosures, FAQ, blog' },
    { id:'crm',     name:'CRM (Salesforce)', status:'connected', last:'1 hour ago',  count:'12,400 records', hint:'Anonymized banking cohorts and policyholder segments' },
    { id:'csv',     name:'CSV upload',       status:'idle',      last:'—',           count:'0 files',      hint:'Drop deposit, claims, broker, or underwriting spreadsheets' },
  ],
  x: {
    hashtags: ['#personalfinance', '#prestito', '#tassi', '#mutui', '#assicurazioni'],
    accounts: ['@finanzaitaliana', '@money_lab', '@banking_watch'],
    posts: 4820,
    rate: '+62/min',
  },
  reddit: {
    subs: ['r/ItalyPersonalFinance', 'r/personalfinance', 'r/Fire', 'r/Insurance'],
    posts: 1340,
    rate: '+18/min',
  },
  linkedin: {
    hashtags: ['#banking', '#insurance', '#personalfinance', '#mortgage', '#fintech'],
    accounts: ['@bancaesempio', '@nordcredit', '@medbancassurance'],
    posts: 2110,
    rate: '+24/min',
    references: [
      'Cleaner disclosure pages drive more advisor callbacks than discount banners.',
      'Embedded protection cover works when the underwriting story is explained upfront.',
      'Corporate clients prefer faster salary-switch flows and fewer document steps.',
    ],
  },
  ticker: [
    { src:'reddit', t:'"Fixed rate every time. I don\'t sleep well with variable…"' },
    { src:'x',      t:'"Cool, another bank ad with \'starting from 4.9%\'…"' },
    { src:'reddit', t:'"Banks treating freelancers like a credit risk in 2026 is wild."' },
    { src:'x',      t:'"If your loan offer requires me to schedule a consulenza I\'m out."' },
    { source:'reddit', t:'"Got the loan in 4 working days. Speed is the product."' },
    { src:'linkedin', t:'"Corporate clients are asking for cleaner disclosures and embedded protection cover."' },
    { src:'linkedin', t:'"Salary-switch incentives matter more than banner ads in the corporate segment."' },
    { src:'x',      t:'"Optional insurance is fine. Mandatory protection cover kills trust."' },
    { src:'reddit', t:'"My CRIF profile is thin after 4 years in Berlin."' },
  ],
};

window.SASP_DATA = { ARCHETYPES, PRODUCT_DEFAULTS, SOURCES_DATA, TENANTS_DATA };
